#!/bin/bash

# shellcheck disable=SC2164
SCRIPT_PATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

installBase() {
  sh "$SCRIPT_PATH"/system/apply-misc-tweaks.sh
  sh "$SCRIPT_PATH"/system/apply-apt-tweaks.sh
  sh "$SCRIPT_PATH"/system/install-docker.sh
  sh "$SCRIPT_PATH"/system/install-base-software.sh
}

installFull() {
  installBase
  sh "$SCRIPT_PATH"/system/add-apt-repos.sh
  sh "$SCRIPT_PATH"/system/install-full-software.sh
  sh "$SCRIPT_PATH"/system/install-kvm.sh
}

case $1 in
    "full")
        installFull
        ;;
    "base")
        installBase
        ;;
    *) echo "Doesn't recognize \"$1\"."
        ;;
esac